-- Notifications / Alerts (Phase 9) — the actionable layer over the prop engine.
-- One row per delivered alert. Generated by the evaluator (src/alerts.js) when the
-- engine's state crosses a threshold on a live ingest, delivered in-app in real
-- time over the user's Socket.IO room. Email/Discord are a later channel.
--
-- Debounce lives in the row: `dedup_key` uniquely identifies an alert instance
-- (account + threshold + cycle, e.g. '314943467:daily_dd_80:2026-07-04'), so an
-- INSERT … ON CONFLICT (dedup_key) DO NOTHING makes a proximity alert fire once per
-- cycle instead of on every equity tick, and a breach fire exactly once.
CREATE TABLE IF NOT EXISTS notifications (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    account_id  BIGINT,                          -- MT5 login the alert is about (null = user-level)
    type        TEXT   NOT NULL,                  -- 'daily_dd_warning' | 'max_dd_warning' | 'breach' | 'trading_days_met' | 'target_reached' | 'phase_passed' | …
    severity    TEXT   NOT NULL DEFAULT 'info',   -- 'info' | 'warning' | 'critical'
    title       TEXT   NOT NULL,
    body        TEXT,
    data        JSONB,                            -- structured context (figures, phase, threshold)
    dedup_key   TEXT   NOT NULL,                  -- account:threshold:cycle — one alert per instance
    read_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One alert per (user, dedup_key): the ON CONFLICT target for the evaluator's
-- debounce. Scoped by user so keys never collide across tenants.
CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_dedup ON notifications (user_id, dedup_key);
-- Feed the notification panel (newest first) + unread badge.
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications (user_id) WHERE read_at IS NULL;
