import { listNotifications, markRead } from '../domain/alerts/notifications.js';

/**
 * In-app alerts. Created by the prop engine during ingest and pushed live over
 * the user's socket room; these routes are the catch-up read and the read receipt.
 *
 * Registered by calling this function on the ROOT app instance rather than through
 * app.register(). A registered plugin gets its own encapsulated context, and a
 * route defined there cannot see decorators or hooks added to the parent
 * afterwards — app.requireAuth would be undefined and the global rate-limit hook
 * would not apply. A plain call keeps every route on the same instance, in the
 * same order, with the same guards it had when these handlers lived in app.js.
 */
export default function notificationRoutes(app) {
  // ---------------------------------------------------------------------------
  // Notifications — in-app alert feed for the logged-in user. Generated by the
  // evaluator on live ingests (rule breaches, proximity warnings, milestones);
  // delivered live over the user's socket room as `notification:new`.
  // ---------------------------------------------------------------------------
  app.get('/api/notifications', { preHandler: app.requireAuth }, async (req) =>
    listNotifications(req.user.uid, Math.min(Number(req.query.limit) || 50, 200))
  );

  app.post('/api/notifications/read', { preHandler: app.requireAuth }, async (req) => {
    const b = req.body ?? {};
    const ids = Array.isArray(b.ids) ? b.ids.map(Number).filter(Number.isFinite) : null;
    const unread = await markRead(req.user.uid, { ids, all: !!b.all });
    return { unread };
  });
}
